"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MoodSectionComponent = void 0;
const jsx_runtime_1 = require("react/jsx-runtime");
const react_1 = require("react");
const MoodSectionComponent = ({ moodSection, onGameClick }) => {
    const [isExpanded, setIsExpanded] = (0, react_1.useState)(false);
    return ((0, jsx_runtime_1.jsxs)("div", { className: "glass-morphism rounded-xl p-6 mb-6 cinematic-shadow", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex items-center justify-between mb-4", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex items-center gap-3", children: [(0, jsx_runtime_1.jsx)("div", { className: `
            w-12 h-12 rounded-xl flex items-center justify-center text-2xl
            ${moodSection.color}
          `, children: moodSection.emoji }), (0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)("h2", { className: "text-xl font-semibold text-white", children: moodSection.name }), (0, jsx_runtime_1.jsx)("p", { className: "text-sm text-gray-400", children: moodSection.description })] })] }), (0, jsx_runtime_1.jsx)("button", { onClick: () => setIsExpanded(!isExpanded), className: "text-gray-400 hover:text-white transition-colors text-lg", children: isExpanded ? '▼' : '▶' })] }), (0, jsx_runtime_1.jsx)("div", { className: `
        grid gap-4 transition-all duration-300
        ${isExpanded ? 'grid-cols-2 md:grid-cols-3 lg:grid-cols-4' : 'grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5'}
      `, children: (isExpanded ? moodSection.games : moodSection.games.slice(0, 5)).map((game) => ((0, jsx_runtime_1.jsxs)("div", { onClick: () => onGameClick?.(game), className: "group cursor-pointer transition-all duration-300 hover:scale-105", children: [(0, jsx_runtime_1.jsxs)("div", { className: "relative aspect-[3/4] rounded-lg overflow-hidden bg-gradient-to-br from-gray-800 to-gray-900", children: [game.coverImage ? ((0, jsx_runtime_1.jsx)("img", { src: game.coverImage, alt: game.title, className: "w-full h-full object-cover transition-transform duration-300 group-hover:scale-110" })) : ((0, jsx_runtime_1.jsx)("div", { className: "w-full h-full flex items-center justify-center", children: (0, jsx_runtime_1.jsx)("div", { className: "w-12 h-12 bg-gradient-to-r from-gaming-primary to-gaming-secondary rounded-lg flex items-center justify-center", children: (0, jsx_runtime_1.jsx)("span", { className: "text-xl", children: "\uD83C\uDFAE" }) }) })), (0, jsx_runtime_1.jsx)("div", { className: "absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300", children: (0, jsx_runtime_1.jsxs)("div", { className: "absolute bottom-0 left-0 right-0 p-3", children: [(0, jsx_runtime_1.jsx)("h4", { className: "text-white font-medium text-sm truncate mb-1", children: game.title }), (0, jsx_runtime_1.jsxs)("div", { className: "flex items-center gap-2 text-xs text-gray-300", children: [game.hoursPlayed && ((0, jsx_runtime_1.jsxs)("span", { children: ["\u23F1\uFE0F ", game.hoursPlayed, "h"] })), game.userRating && ((0, jsx_runtime_1.jsxs)("span", { children: ["\u2B50 ", game.userRating] }))] })] }) }), game.playStatus && ((0, jsx_runtime_1.jsx)("div", { className: "absolute top-2 right-2", children: (0, jsx_runtime_1.jsx)("span", { className: `
                    px-2 py-1 rounded-full text-xs font-medium
                    ${game.playStatus === 'playing' ? 'bg-green-500/80 text-white' : ''}
                    ${game.playStatus === 'completed' ? 'bg-blue-500/80 text-white' : ''}
                    ${game.playStatus === 'backlog' ? 'bg-yellow-500/80 text-white' : ''}
                    ${game.playStatus === 'abandoned' ? 'bg-red-500/80 text-white' : ''}
                  `, children: game.playStatus }) }))] }), (0, jsx_runtime_1.jsx)("h3", { className: "text-white text-sm font-medium mt-2 truncate group-hover:text-gaming-accent transition-colors", children: game.title })] }, game.id))) }), moodSection.games.length > 5 && ((0, jsx_runtime_1.jsx)("div", { className: "mt-4 text-center", children: (0, jsx_runtime_1.jsx)("button", { onClick: () => setIsExpanded(!isExpanded), className: "text-accent-400 hover:text-accent-300 transition-colors text-sm font-medium", children: isExpanded ? `Show Less` : `Show ${moodSection.games.length - 5} More` }) })), moodSection.games.length === 0 && ((0, jsx_runtime_1.jsxs)("div", { className: "text-center py-8", children: [(0, jsx_runtime_1.jsx)("div", { className: "w-16 h-16 bg-gray-800 rounded-xl mx-auto mb-3 flex items-center justify-center", children: (0, jsx_runtime_1.jsx)("span", { className: "text-2xl opacity-50", children: moodSection.emoji }) }), (0, jsx_runtime_1.jsx)("p", { className: "text-gray-400", children: "No games in this mood yet" }), (0, jsx_runtime_1.jsx)("p", { className: "text-sm text-gray-500 mt-1", children: "Start tagging games with emotions to see them here" })] }))] }));
};
exports.MoodSectionComponent = MoodSectionComponent;
