"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.WhatShouldIBuySection = void 0;
const jsx_runtime_1 = require("react/jsx-runtime");
const homeHelpers_1 = require("../utils/homeHelpers");
const WhatShouldIBuySection = ({ games }) => {
    const recommendations = (0, homeHelpers_1.getMockStoreRecommendations)(games);
    return ((0, jsx_runtime_1.jsxs)("section", { className: "mb-12", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex items-center justify-between mb-6", children: [(0, jsx_runtime_1.jsxs)("h2", { className: "text-3xl font-bold text-white flex items-center gap-3", children: [(0, jsx_runtime_1.jsx)("span", { className: "text-2xl", children: "\uD83D\uDED2" }), "What Should I Buy?"] }), (0, jsx_runtime_1.jsx)("div", { className: "text-sm text-gray-400", children: "Based on your library" })] }), (0, jsx_runtime_1.jsxs)("div", { className: "glass-morphism rounded-xl p-6", children: [(0, jsx_runtime_1.jsx)("div", { className: "mb-4", children: (0, jsx_runtime_1.jsx)("p", { className: "text-gray-300 text-sm", children: "Coming Soon: Real Store Integration" }) }), (0, jsx_runtime_1.jsx)("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4", children: recommendations.map((rec) => ((0, jsx_runtime_1.jsxs)("div", { className: "bg-gray-800/50 rounded-lg overflow-hidden hover:bg-gray-800/70 transition-all cursor-pointer", children: [(0, jsx_runtime_1.jsxs)("div", { className: "aspect-video w-full overflow-hidden rounded-t-md", children: [rec.image ? ((0, jsx_runtime_1.jsx)("img", { src: rec.image, alt: rec.title, className: "w-full h-full object-cover", onError: (e) => {
                                                // Fallback to placeholder if image fails to load
                                                const target = e.target;
                                                target.style.display = 'none';
                                                target.nextElementSibling?.classList.remove('hidden');
                                            } })) : null, (0, jsx_runtime_1.jsx)("div", { className: "hidden w-full h-full flex items-center justify-center bg-gradient-to-br from-gaming-primary/20 to-gaming-secondary/20 text-4xl text-gray-500", children: "\uD83C\uDFAE" })] }), (0, jsx_runtime_1.jsxs)("div", { className: "p-4 space-y-3", children: [(0, jsx_runtime_1.jsx)("h3", { className: "font-semibold text-white", children: rec.title }), (0, jsx_runtime_1.jsxs)("div", { className: "flex items-center gap-2 text-sm text-gray-400", children: [(0, jsx_runtime_1.jsx)("span", { className: "px-2 py-1 bg-gaming-accent/20 rounded text-gaming-accent", children: rec.genre }), rec.rating && ((0, jsx_runtime_1.jsxs)("span", { children: ["\u2B50 ", rec.rating] }))] }), (0, jsx_runtime_1.jsx)("p", { className: "text-sm text-gray-300 line-clamp-2", children: rec.description }), (0, jsx_runtime_1.jsx)("div", { className: "text-sm text-gaming-accent font-medium", children: rec.reason }), rec.price && ((0, jsx_runtime_1.jsx)("div", { className: "text-lg font-bold text-white", children: rec.price })), (0, jsx_runtime_1.jsx)("button", { disabled: true, className: "w-full px-3 py-2 bg-gray-700 text-gray-400 rounded text-sm font-medium cursor-not-allowed", children: "Coming Soon" })] })] }, rec.id))) }), (0, jsx_runtime_1.jsx)("div", { className: "mt-6 text-center", children: (0, jsx_runtime_1.jsx)("p", { className: "text-sm text-gray-400", children: "\uD83D\uDE80 Store integration coming soon! These recommendations will be linked to real purchase options." }) })] })] }));
};
exports.WhatShouldIBuySection = WhatShouldIBuySection;
