"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PriceBadge = exports.TagsList = exports.InfoSection = exports.TrailerPlayer = exports.ScreenshotCarousel = void 0;
var ScreenshotCarousel_1 = require("./ScreenshotCarousel");
Object.defineProperty(exports, "ScreenshotCarousel", { enumerable: true, get: function () { return ScreenshotCarousel_1.ScreenshotCarousel; } });
var TrailerPlayer_1 = require("./TrailerPlayer");
Object.defineProperty(exports, "TrailerPlayer", { enumerable: true, get: function () { return TrailerPlayer_1.TrailerPlayer; } });
var InfoSection_1 = require("./InfoSection");
Object.defineProperty(exports, "InfoSection", { enumerable: true, get: function () { return InfoSection_1.InfoSection; } });
var TagsList_1 = require("./TagsList");
Object.defineProperty(exports, "TagsList", { enumerable: true, get: function () { return TagsList_1.TagsList; } });
var PriceBadge_1 = require("./PriceBadge");
Object.defineProperty(exports, "PriceBadge", { enumerable: true, get: function () { return PriceBadge_1.PriceBadge; } });
