"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.GameCardSkeleton = GameCardSkeleton;
exports.GameGridSkeleton = GameGridSkeleton;
exports.VirtualGridSkeleton = VirtualGridSkeleton;
const jsx_runtime_1 = require("react/jsx-runtime");
function GameCardSkeleton() {
    return ((0, jsx_runtime_1.jsx)("div", { className: "relative group cursor-pointer transition-all duration-300 transform animate-pulse", children: (0, jsx_runtime_1.jsxs)("div", { className: "glass-morphism rounded-2xl overflow-hidden border border-gray-700/30 transition-all duration-300", children: [(0, jsx_runtime_1.jsx)("div", { className: "relative w-full h-52 overflow-hidden bg-gradient-to-br from-gray-700 to-gray-800", children: (0, jsx_runtime_1.jsx)("div", { className: "absolute inset-0 skeleton-shimmer" }) }), (0, jsx_runtime_1.jsxs)("div", { className: "absolute inset-0 bg-gradient-to-t from-black/80 via-black/50 to-transparent p-5 flex flex-col justify-end", children: [(0, jsx_runtime_1.jsx)("div", { className: "h-6 bg-gray-600 rounded mb-3 w-3/4 animate-pulse" }), (0, jsx_runtime_1.jsxs)("div", { className: "flex gap-1.5 mb-3", children: [(0, jsx_runtime_1.jsx)("div", { className: "h-5 bg-gray-700 rounded px-2.5 w-16 animate-pulse" }), (0, jsx_runtime_1.jsx)("div", { className: "h-5 bg-gray-700 rounded px-2.5 w-12 animate-pulse" })] }), (0, jsx_runtime_1.jsxs)("div", { className: "flex gap-1.5 mb-3", children: [(0, jsx_runtime_1.jsx)("div", { className: "h-5 bg-gray-700 rounded px-2.5 w-14 animate-pulse" }), (0, jsx_runtime_1.jsx)("div", { className: "h-5 bg-gray-700 rounded px-2.5 w-12 animate-pulse" }), (0, jsx_runtime_1.jsx)("div", { className: "h-5 bg-gray-700 rounded px-2.5 w-10 animate-pulse" })] }), (0, jsx_runtime_1.jsxs)("div", { className: "flex items-center justify-between mb-3 pb-3 border-b border-gray-700/30", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex items-center gap-2", children: [(0, jsx_runtime_1.jsx)("div", { className: "w-2 h-2 bg-gray-600 rounded-full animate-pulse" }), (0, jsx_runtime_1.jsx)("div", { className: "h-4 bg-gray-600 rounded w-16 animate-pulse" })] }), (0, jsx_runtime_1.jsx)("div", { className: "h-4 bg-gray-600 rounded w-8 animate-pulse" })] }), (0, jsx_runtime_1.jsxs)("div", { className: "flex gap-2", children: [(0, jsx_runtime_1.jsx)("div", { className: "flex-1 h-8 bg-gray-700 rounded-lg animate-pulse" }), (0, jsx_runtime_1.jsx)("div", { className: "w-12 h-8 bg-gray-700 rounded-lg animate-pulse" }), (0, jsx_runtime_1.jsx)("div", { className: "w-12 h-8 bg-gray-700 rounded-lg animate-pulse" }), (0, jsx_runtime_1.jsx)("div", { className: "w-20 h-8 bg-gray-700 rounded-lg animate-pulse" })] })] })] }) }));
}
function GameGridSkeleton({ count = 8 }) {
    return ((0, jsx_runtime_1.jsx)("div", { className: "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4 gap-6 lg:gap-8", children: Array.from({ length: count }).map((_, index) => ((0, jsx_runtime_1.jsx)(GameCardSkeleton, {}, index))) }));
}
function VirtualGridSkeleton({ count = 20 }) {
    return ((0, jsx_runtime_1.jsx)("div", { className: "space-y-6", children: Array.from({ length: count }).map((_, index) => ((0, jsx_runtime_1.jsx)("div", { className: "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4 gap-6 lg:gap-8", children: Array.from({ length: 4 }).map((_, cardIndex) => ((0, jsx_runtime_1.jsx)(GameCardSkeleton, {}, `${index}-${cardIndex}`))) }, index))) }));
}
