"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.mockLibraryGames = void 0;
/**
 * Clean synthetic game library for persona stress-testing
 * Matches the canonical Game interface exactly
 */
exports.mockLibraryGames = [
    {
        id: 'dark-souls-remastered',
        title: 'Dark Souls Remastered',
        description: 'The acclaimed dark fantasy action RPG returns. Master brutal combat and intricate level design.',
        backgroundImages: [],
        coverImage: 'https://cdn.cloudflare.steamstatic.com/steam/apps/570/header.jpg',
        releaseDate: new Date('2018-05-25'),
        developer: 'FromSoftware',
        publisher: 'Bandai Namco Entertainment',
        genres: ['action', 'rpg'],
        subgenres: ['soulslike', 'dark-fantasy'],
        platforms: [{ id: 'steam', name: 'Steam', code: 'steam', isConnected: true }],
        emotionalTags: ['Competitive', 'Focused'],
        userRating: 9,
        globalRating: 8.5,
        playStatus: 'completed',
        hoursPlayed: 127,
        lastPlayed: new Date('2024-01-15'),
        addedAt: new Date('2023-06-10'),
        notes: 'Amazing challenging experience',
        isFavorite: true,
        releaseYear: 2018,
        achievements: { unlocked: 42, total: 43 }
    },
    {
        id: 'hades',
        title: 'Hades',
        description: 'Defy the god of the dead as you hack and slash out of the Underworld in this rogue-like dungeon crawler.',
        backgroundImages: [],
        coverImage: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1145400/header.jpg',
        releaseDate: new Date('2020-09-17'),
        developer: 'Supergiant Games',
        publisher: 'Supergiant Games',
        genres: ['action', 'roguelike'],
        subgenres: ['rogue-lite', 'indie'],
        platforms: [{ id: 'steam', name: 'Steam', code: 'steam', isConnected: true }],
        emotionalTags: ['Competitive', 'Energetic'],
        userRating: 9.5,
        globalRating: 9.2,
        playStatus: 'playing',
        hoursPlayed: 89,
        lastPlayed: new Date('2024-01-20'),
        addedAt: new Date('2023-08-15'),
        notes: 'Addictive gameplay loop',
        isFavorite: true,
        releaseYear: 2020,
        achievements: { unlocked: 38, total: 50 }
    },
    {
        id: 'portal-2',
        title: 'Portal 2',
        description: 'The highly anticipated sequel to 2007\'s Game of the Year, Portal 2 is a hilariously mind-bending adventure.',
        backgroundImages: [],
        coverImage: 'https://cdn.cloudflare.steamstatic.com/steam/apps/620/header.jpg',
        releaseDate: new Date('2011-04-19'),
        developer: 'Valve',
        publisher: 'Valve',
        genres: ['puzzle', 'platformer'],
        subgenres: ['physics-puzzle', 'comedy'],
        platforms: [{ id: 'steam', name: 'Steam', code: 'steam', isConnected: true }],
        emotionalTags: ['Chill', 'Creative'],
        userRating: 9.8,
        globalRating: 9.5,
        playStatus: 'completed',
        hoursPlayed: 12,
        lastPlayed: new Date('2023-12-01'),
        addedAt: new Date('2023-05-20'),
        notes: 'Brilliant puzzles and story',
        isFavorite: false,
        releaseYear: 2011,
        achievements: { unlocked: 50, total: 50 }
    },
    {
        id: 'final-fantasy-xiv',
        title: 'Final Fantasy XIV Online',
        description: 'Take part in an epic and ever-changing FINAL FANTASY as you adventure and explore with friends.',
        backgroundImages: [],
        coverImage: 'https://via.placeholder.com/300x400/4169E1/FFFFFF?text=FFXIV',
        releaseDate: new Date('2013-08-27'),
        developer: 'Square Enix',
        publisher: 'Square Enix',
        genres: ['mmorpg', 'rpg'],
        subgenres: ['fantasy', 'online-multiplayer'],
        platforms: [{ id: 'steam', name: 'Steam', code: 'steam', isConnected: true }],
        emotionalTags: ['Social', 'Story'],
        userRating: 9.0,
        globalRating: 8.8,
        playStatus: 'playing',
        hoursPlayed: 456,
        lastPlayed: new Date('2024-01-21'),
        addedAt: new Date('2022-03-15'),
        notes: 'Best MMO experience',
        isFavorite: true,
        releaseYear: 2013,
        achievements: { unlocked: 245, total: 500 }
    },
    {
        id: 'counter-strike-2',
        title: 'Counter-Strike 2',
        description: 'Counter-Strike 2 is a free upgrade to CS:GO, building on the tactical foundation.',
        backgroundImages: [],
        coverImage: 'https://via.placeholder.com/300x400/FFA500/FFFFFF?text=CS2',
        releaseDate: new Date('2023-09-27'),
        developer: 'Valve',
        publisher: 'Valve',
        genres: ['fps', 'competitive'],
        subgenres: ['tactical-shooter', 'multiplayer'],
        platforms: [{ id: 'steam', name: 'Steam', code: 'steam', isConnected: true }],
        emotionalTags: ['Competitive', 'Energetic'],
        userRating: 8.5,
        globalRating: 8.2,
        playStatus: 'playing',
        hoursPlayed: 234,
        lastPlayed: new Date('2024-01-21'),
        addedAt: new Date('2023-10-01'),
        notes: 'Intense competitive matches',
        isFavorite: false,
        releaseYear: 2023,
        achievements: { unlocked: 15, total: 30 }
    },
    {
        id: 'it-takes-two',
        title: 'It Takes Two',
        description: 'Embark on the craziest journey of your life in It Takes Two, a genre-bending platform adventure.',
        backgroundImages: [],
        coverImage: 'https://via.placeholder.com/300x400/FF69B4/FFFFFF?text=It+Takes+Two',
        releaseDate: new Date('2021-03-26'),
        developer: 'Hazelight Studios',
        publisher: 'Electronic Arts',
        genres: ['adventure', 'platformer'],
        subgenres: ['co-op', 'comedy'],
        platforms: [{ id: 'steam', name: 'Steam', code: 'steam', isConnected: true }],
        emotionalTags: ['Social', 'Chill'],
        userRating: 9.2,
        globalRating: 8.9,
        playStatus: 'completed',
        hoursPlayed: 14,
        lastPlayed: new Date('2023-11-15'),
        addedAt: new Date('2023-09-01'),
        notes: 'Perfect co-op experience',
        isFavorite: true,
        releaseYear: 2021,
        achievements: { unlocked: 35, total: 35 }
    },
    {
        id: 'civilization-vi',
        title: 'Civilization VI',
        description: 'Build an empire to stand the test of time in this turn-based strategy classic.',
        backgroundImages: [],
        coverImage: 'https://via.placeholder.com/300x400/8B4513/FFFFFF?text=Civ+VI',
        releaseDate: new Date('2016-10-21'),
        developer: 'Firaxis Games',
        publisher: '2K Games',
        genres: ['strategy', 'turn-based'],
        subgenres: ['4x', 'historical'],
        platforms: [{ id: 'steam', name: 'Steam', code: 'steam', isConnected: true }],
        emotionalTags: ['Focused', 'Creative'],
        userRating: 8.8,
        globalRating: 8.7,
        playStatus: 'playing',
        hoursPlayed: 189,
        lastPlayed: new Date('2024-01-19'),
        addedAt: new Date('2022-01-10'),
        notes: 'Deep strategic gameplay',
        isFavorite: false,
        releaseYear: 2016,
        achievements: { unlocked: 89, total: 150 }
    },
    {
        id: 'the-witcher-3',
        title: 'The Witcher 3: Wild Hunt',
        description: 'You are Geralt of Rivia, mercenary monster slayer. Before you stands a war-torn world.',
        backgroundImages: [],
        coverImage: 'https://cdn.cloudflare.steamstatic.com/steam/apps/292030/header.jpg',
        releaseDate: new Date('2015-05-19'),
        developer: 'CD Projekt Red',
        publisher: 'CD Projekt Red',
        genres: ['rpg', 'open-world'],
        subgenres: ['fantasy', 'story-rich'],
        platforms: [{ id: 'steam', name: 'Steam', code: 'steam', isConnected: true }],
        emotionalTags: ['Story', 'Focused'],
        userRating: 9.7,
        globalRating: 9.5,
        playStatus: 'completed',
        hoursPlayed: 156,
        lastPlayed: new Date('2023-10-20'),
        addedAt: new Date('2022-06-15'),
        notes: 'Incredible storytelling',
        isFavorite: true,
        releaseYear: 2015,
        achievements: { unlocked: 67, total: 78 }
    },
    {
        id: 'stardew-valley',
        title: 'Stardew Valley',
        description: 'You\'ve inherited your grandfather\'s old farm plot in Stardew Valley. Armed with hand-me-down tools.',
        backgroundImages: [],
        coverImage: 'https://cdn.cloudflare.steamstatic.com/steam/apps/413150/header.jpg',
        releaseDate: new Date('2016-02-26'),
        developer: 'ConcernedApe',
        publisher: 'ConcernedApe',
        genres: ['simulation', 'casual'],
        subgenres: ['farming', 'relaxing'],
        platforms: [{ id: 'steam', name: 'Steam', code: 'steam', isConnected: true }],
        emotionalTags: ['Chill', 'Creative'],
        userRating: 9.5,
        globalRating: 9.3,
        playStatus: 'playing',
        hoursPlayed: 78,
        lastPlayed: new Date('2024-01-20'),
        addedAt: new Date('2023-07-20'),
        notes: 'Relaxing and addictive',
        isFavorite: true,
        releaseYear: 2016,
        achievements: { unlocked: 23, total: 40 }
    },
    {
        id: 'resident-evil-8',
        title: 'Resident Evil 8 Village',
        description: 'Experience survival horror like never before in the eighth major installment.',
        backgroundImages: [],
        coverImage: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1196590/header.jpg',
        releaseDate: new Date('2021-05-07'),
        developer: 'Capcom',
        publisher: 'Capcom',
        genres: ['horror', 'survival'],
        subgenres: ['third-person-shooter', 'zombies'],
        platforms: [{ id: 'steam', name: 'Steam', code: 'steam', isConnected: true }],
        emotionalTags: ['Competitive', 'Focused'],
        userRating: 8.2,
        globalRating: 8.0,
        playStatus: 'paused',
        hoursPlayed: 8,
        lastPlayed: new Date('2024-01-10'),
        addedAt: new Date('2023-11-01'),
        notes: 'Too scary for me',
        isFavorite: false,
        releaseYear: 2021,
        achievements: { unlocked: 12, total: 30 }
    },
    {
        id: 'forza-horizon-5',
        title: 'Forza Horizon 5',
        description: 'Your Ultimate Horizon Adventure awaits! Explore the vibrant open world of Mexico.',
        backgroundImages: [],
        coverImage: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1551360/header.jpg',
        releaseDate: new Date('2021-11-09'),
        developer: 'Playground Games',
        publisher: 'Xbox Game Studios',
        genres: ['racing', 'open-world'],
        subgenres: ['arcade-racing', 'multiplayer'],
        platforms: [{ id: 'steam', name: 'Steam', code: 'steam', isConnected: true }],
        emotionalTags: ['Energetic', 'Competitive'],
        userRating: 8.7,
        globalRating: 8.5,
        playStatus: 'playing',
        hoursPlayed: 45,
        lastPlayed: new Date('2024-01-18'),
        addedAt: new Date('2023-12-15'),
        notes: 'Beautiful open world',
        isFavorite: false,
        releaseYear: 2021,
        achievements: { unlocked: 56, total: 100 }
    },
    {
        id: 'celeste',
        title: 'Celeste',
        description: 'Help Madeline survive her inner demons on her journey to the top of Celeste Mountain.',
        backgroundImages: [],
        coverImage: 'https://cdn.cloudflare.steamstatic.com/steam/apps/504230/header.jpg',
        releaseDate: new Date('2018-01-25'),
        developer: 'Maddy Makes Games',
        publisher: 'Maddy Makes Games',
        genres: ['platformer', 'indie'],
        subgenres: ['precision-platformer', 'story-rich'],
        platforms: [{ id: 'steam', name: 'Steam', code: 'steam', isConnected: true }],
        emotionalTags: ['Competitive', 'Chill'],
        userRating: 9.3,
        globalRating: 9.1,
        playStatus: 'completed',
        hoursPlayed: 23,
        lastPlayed: new Date('2023-09-10'),
        addedAt: new Date('2023-05-25'),
        notes: 'Challenging but fair',
        isFavorite: true,
        releaseYear: 2018,
        achievements: { unlocked: 25, total: 25 }
    },
    {
        id: 'apex-legends',
        title: 'Apex Legends',
        description: 'Conquer with character in Apex Legends, a free-to-play hero shooter.',
        backgroundImages: [],
        coverImage: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1172470/header.jpg',
        releaseDate: new Date('2019-02-04'),
        developer: 'Respawn Entertainment',
        publisher: 'Electronic Arts',
        genres: ['fps', 'battle-royale'],
        subgenres: ['hero-shooter', 'multiplayer'],
        platforms: [{ id: 'steam', name: 'Steam', code: 'steam', isConnected: true }],
        emotionalTags: ['Competitive', 'Energetic'],
        userRating: 8.4,
        globalRating: 8.2,
        playStatus: 'playing',
        hoursPlayed: 167,
        lastPlayed: new Date('2024-01-21'),
        addedAt: new Date('2022-02-14'),
        notes: 'Fast-paced action',
        isFavorite: false,
        releaseYear: 2019,
        achievements: { unlocked: 45, total: 100 }
    },
    {
        id: 'cities-skylines',
        title: 'Cities: Skylines',
        description: 'Cities: Skylines is a modern take on the classic city simulation.',
        backgroundImages: [],
        coverImage: 'https://cdn.cloudflare.steamstatic.com/steam/apps/255710/header.jpg',
        releaseDate: new Date('2015-03-10'),
        developer: 'Colossal Order',
        publisher: 'Paradox Interactive',
        genres: ['simulation', 'strategy'],
        subgenres: ['city-builder', 'management'],
        platforms: [{ id: 'steam', name: 'Steam', code: 'steam', isConnected: true }],
        emotionalTags: ['Creative', 'Focused'],
        userRating: 9.0,
        globalRating: 8.8,
        playStatus: 'playing',
        hoursPlayed: 98,
        lastPlayed: new Date('2024-01-17'),
        addedAt: new Date('2022-08-20'),
        notes: 'Addictive city building',
        isFavorite: false,
        releaseYear: 2015,
        achievements: { unlocked: 34, total: 50 }
    },
    {
        id: 'diablo-4',
        title: 'Diablo IV',
        description: 'The legendary RPG returns. Darkness returns to Sanctuary.',
        backgroundImages: [],
        coverImage: 'https://cdn.cloudflare.steamstatic.com/steam/apps/227300/header.jpg',
        releaseDate: new Date('2023-06-06'),
        developer: 'Blizzard Entertainment',
        publisher: 'Blizzard Entertainment',
        genres: ['action', 'rpg', 'hack-and-slash'],
        subgenres: ['dungeon-crawler', 'dark-fantasy'],
        platforms: [{ id: 'steam', name: 'Steam', code: 'steam', isConnected: true }],
        emotionalTags: ['Competitive', 'Energetic'],
        userRating: 8.6,
        globalRating: 8.4,
        playStatus: 'playing',
        hoursPlayed: 67,
        lastPlayed: new Date('2024-01-21'),
        addedAt: new Date('2023-06-10'),
        notes: 'Dark and satisfying',
        isFavorite: true,
        releaseYear: 2023,
        achievements: { unlocked: 28, total: 50 }
    },
    {
        id: 'fifa-24',
        title: 'EA Sports FC 24',
        description: 'EA Sports FC 24 brings you the world of football with over 19,000 players.',
        backgroundImages: [],
        coverImage: 'https://via.placeholder.com/300x400/00FF00/FFFFFF?text=FC+24',
        releaseDate: new Date('2023-09-29'),
        developer: 'EA Vancouver',
        publisher: 'EA Sports',
        genres: ['sports', 'simulation'],
        subgenres: ['football', 'multiplayer'],
        platforms: [{ id: 'steam', name: 'Steam', code: 'steam', isConnected: true }],
        emotionalTags: ['Competitive', 'Social'],
        userRating: 7.8,
        globalRating: 7.5,
        playStatus: 'playing',
        hoursPlayed: 34,
        lastPlayed: new Date('2024-01-20'),
        addedAt: new Date('2023-10-15'),
        notes: 'Football with friends',
        isFavorite: false,
        releaseYear: 2023,
        achievements: { unlocked: 12, total: 30 }
    },
    {
        id: 'minecraft',
        title: 'Minecraft',
        description: 'Explore infinite worlds and build everything from the simplest of homes to the grandest of castles.',
        backgroundImages: [],
        coverImage: 'https://cdn.cloudflare.steamstatic.com/steam/apps/239140/header.jpg',
        releaseDate: new Date('2011-11-18'),
        developer: 'Mojang Studios',
        publisher: 'Mojang Studios',
        genres: ['sandbox', 'survival'],
        subgenres: ['crafting', 'creative'],
        platforms: [{ id: 'steam', name: 'Steam', code: 'steam', isConnected: true }],
        emotionalTags: ['Creative', 'Chill'],
        userRating: 9.4,
        globalRating: 9.3,
        playStatus: 'playing',
        hoursPlayed: 234,
        lastPlayed: new Date('2024-01-19'),
        addedAt: new Date('2021-03-10'),
        notes: 'Endless creativity',
        isFavorite: true,
        releaseYear: 2011,
        achievements: { unlocked: 45, total: 100 }
    },
    {
        id: 'metal-gear-solid-v',
        title: 'Metal Gear Solid V: The Phantom Pain',
        description: 'Ushering in a new era for the franchise with cutting-edge technology powered by Fox Engine.',
        backgroundImages: [],
        coverImage: 'https://via.placeholder.com/300x400/000080/FFFFFF?text=MGSV',
        releaseDate: new Date('2015-09-01'),
        developer: 'Kojima Productions',
        publisher: 'Konami',
        genres: ['stealth', 'action'],
        subgenres: ['tactical', 'open-world'],
        platforms: [{ id: 'steam', name: 'Steam', code: 'steam', isConnected: true }],
        emotionalTags: ['Focused', 'Chill'],
        userRating: 8.9,
        globalRating: 8.7,
        playStatus: 'unplayed',
        hoursPlayed: 0,
        lastPlayed: undefined,
        addedAt: new Date('2023-12-01'),
        notes: 'Planning to play soon',
        isFavorite: false,
        releaseYear: 2015,
        achievements: { unlocked: 0, total: 50 }
    },
    {
        id: 'street-fighter-6',
        title: 'Street Fighter 6',
        description: 'Street Fighter 6 features groundbreaking crossplay technology.',
        backgroundImages: [],
        coverImage: 'https://via.placeholder.com/300x400/FFD700/FFFFFF?text=SF6',
        releaseDate: new Date('2023-06-02'),
        developer: 'Capcom',
        publisher: 'Capcom',
        genres: ['fighting', 'competitive'],
        subgenres: ['arcade', 'multiplayer'],
        platforms: [{ id: 'steam', name: 'Steam', code: 'steam', isConnected: true }],
        emotionalTags: ['Competitive', 'Energetic'],
        userRating: 8.3,
        globalRating: 8.1,
        playStatus: 'playing',
        hoursPlayed: 56,
        lastPlayed: new Date('2024-01-21'),
        addedAt: new Date('2023-06-05'),
        notes: 'Classic fighting',
        isFavorite: false,
        releaseYear: 2023,
        achievements: { unlocked: 23, total: 40 }
    },
    {
        id: 'life-is-strange',
        title: 'Life is Strange',
        description: 'Experience a bold new era in interactive entertainment with Life is Strange.',
        backgroundImages: [],
        coverImage: 'https://via.placeholder.com/300x400/87CEEB/FFFFFF?text=Life+is+Strange',
        releaseDate: new Date('2015-01-30'),
        developer: 'Dontnod Entertainment',
        publisher: 'Square Enix',
        genres: ['adventure', 'visual-novel'],
        subgenres: ['story-rich', 'choice-driven'],
        platforms: [{ id: 'steam', name: 'Steam', code: 'steam', isConnected: true }],
        emotionalTags: ['Story', 'Chill'],
        userRating: 8.8,
        globalRating: 8.6,
        playStatus: 'completed',
        hoursPlayed: 18,
        lastPlayed: new Date('2023-08-15'),
        addedAt: new Date('2023-04-10'),
        notes: 'Emotional story',
        isFavorite: true,
        releaseYear: 2015,
        achievements: { unlocked: 30, total: 30 }
    },
    {
        id: 'bloons-td-6',
        title: 'Bloons TD 6',
        description: 'The Bloons are back and better than ever! Get ready for a massive 3D tower defense game.',
        backgroundImages: [],
        coverImage: 'https://via.placeholder.com/300x400/FF69B4/FFFFFF?text=BTD6',
        releaseDate: new Date('2018-12-18'),
        developer: 'Ninja Kiwi',
        publisher: 'Ninja Kiwi',
        genres: ['tower-defense', 'strategy'],
        subgenres: ['casual', 'colorful'],
        platforms: [{ id: 'steam', name: 'Steam', code: 'steam', isConnected: true }],
        emotionalTags: ['Chill', 'Creative'],
        userRating: 8.5,
        globalRating: 8.3,
        playStatus: 'playing',
        hoursPlayed: 89,
        lastPlayed: new Date('2024-01-21'),
        addedAt: new Date('2022-11-20'),
        notes: 'Fun tower defense',
        isFavorite: false,
        releaseYear: 2018,
        achievements: { unlocked: 67, total: 100 }
    },
    {
        id: 'hearthstone',
        title: 'Hearthstone',
        description: 'Hearthstone is a digital collectible card game set in the Warcraft universe.',
        backgroundImages: [],
        coverImage: 'https://via.placeholder.com/300x400/FFD700/FFFFFF?text=Hearthstone',
        releaseDate: new Date('2014-03-11'),
        developer: 'Blizzard Entertainment',
        publisher: 'Blizzard Entertainment',
        genres: ['card-game', 'strategy'],
        subgenres: ['digital-card-game', 'multiplayer'],
        platforms: [{ id: 'steam', name: 'Steam', code: 'steam', isConnected: true }],
        emotionalTags: ['Focused', 'Social'],
        userRating: 8.2,
        globalRating: 8.0,
        playStatus: 'paused',
        hoursPlayed: 145,
        lastPlayed: new Date('2023-12-15'),
        addedAt: new Date('2021-06-15'),
        notes: 'Strategic card game',
        isFavorite: false,
        releaseYear: 2014,
        achievements: { unlocked: 89, total: 150 }
    },
    {
        id: 'hollow-knight',
        title: 'Hollow Knight',
        description: 'Forge your own path in Hollow Knight! An epic action adventure through a ruined kingdom.',
        backgroundImages: [],
        coverImage: 'https://via.placeholder.com/300x400/4B0082/FFFFFF?text=Hollow+Knight',
        releaseDate: new Date('2017-02-24'),
        developer: 'Team Cherry',
        publisher: 'Team Cherry',
        genres: ['platformer', 'metroidvania'],
        subgenres: ['indie', 'challenging'],
        platforms: [{ id: 'steam', name: 'Steam', code: 'steam', isConnected: true }],
        emotionalTags: ['Competitive', 'Chill'],
        userRating: 9.4,
        globalRating: 9.2,
        playStatus: 'completed',
        hoursPlayed: 67,
        lastPlayed: new Date('2023-10-05'),
        addedAt: new Date('2023-02-15'),
        notes: 'Beautiful metroidvania',
        isFavorite: true,
        releaseYear: 2017,
        achievements: { unlocked: 56, total: 112 }
    },
    {
        id: 'two-point-hospital',
        title: 'Two Point Hospital',
        description: 'Design and build your own hospital in this management sim.',
        backgroundImages: [],
        coverImage: 'https://via.placeholder.com/300x400/00CED1/FFFFFF?text=Two+Point+Hospital',
        releaseDate: new Date('2018-08-30'),
        developer: 'Two Point Studios',
        publisher: 'Sega',
        genres: ['simulation', 'management'],
        subgenres: ['hospital-sim', 'humorous'],
        platforms: [{ id: 'steam', name: 'Steam', code: 'steam', isConnected: true }],
        emotionalTags: ['Creative', 'Chill'],
        userRating: 8.7,
        globalRating: 8.5,
        playStatus: 'playing',
        hoursPlayed: 34,
        lastPlayed: new Date('2024-01-18'),
        addedAt: new Date('2023-09-20'),
        notes: 'Funny hospital sim',
        isFavorite: false,
        releaseYear: 2018,
        achievements: { unlocked: 23, total: 50 }
    }
];
