"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TraitModal = void 0;
const jsx_runtime_1 = require("react/jsx-runtime");
const TraitModal = ({ isOpen, onClose, trait }) => {
    if (!isOpen)
        return null;
    return ((0, jsx_runtime_1.jsx)("div", { className: "fixed inset-0 bg-black/80 backdrop-blur-sm flex items-center justify-center z-50 p-4", onClick: onClose, children: (0, jsx_runtime_1.jsxs)("div", { className: "glass-morphism rounded-2xl p-8 max-w-2xl w-full max-h-[80vh] overflow-y-auto border border-white/20", onClick: (e) => e.stopPropagation(), children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex items-center justify-between mb-6", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex items-center gap-4", children: [(0, jsx_runtime_1.jsx)("div", { className: "text-4xl", children: trait.icon }), (0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)("h2", { className: "text-2xl font-bold text-white", children: trait.label }), (0, jsx_runtime_1.jsx)("p", { className: "text-gaming-accent font-medium", children: trait.value })] })] }), (0, jsx_runtime_1.jsx)("button", { onClick: onClose, className: "text-gray-400 hover:text-white transition-colors text-2xl", children: "\u00D7" })] }), (0, jsx_runtime_1.jsxs)("div", { className: "space-y-6", children: [(0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)("h3", { className: "text-lg font-semibold text-white mb-2", children: "About This Trait" }), (0, jsx_runtime_1.jsx)("p", { className: "text-gray-300 leading-relaxed", children: trait.fullDescription })] }), (0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)("h3", { className: "text-lg font-semibold text-white mb-2", children: "How We Discovered This" }), (0, jsx_runtime_1.jsx)("p", { className: "text-gray-300 leading-relaxed", children: trait.inference })] }), (0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)("h3", { className: "text-lg font-semibold text-white mb-2", children: "Impact on Your Archetype" }), (0, jsx_runtime_1.jsx)("p", { className: "text-gray-300 leading-relaxed", children: trait.archetypeEffect })] }), (0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)("h3", { className: "text-lg font-semibold text-white mb-2", children: "Perfect Game Types for You" }), (0, jsx_runtime_1.jsx)("div", { className: "grid grid-cols-2 md:grid-cols-3 gap-3", children: trait.suggestedGames.map((game, index) => ((0, jsx_runtime_1.jsx)("div", { className: "glass-morphism rounded-lg p-3 text-center hover:bg-white/10 transition-colors cursor-pointer", children: (0, jsx_runtime_1.jsx)("div", { className: "text-gaming-accent font-medium", children: game }) }, index))) })] })] }), (0, jsx_runtime_1.jsx)("div", { className: "mt-8 pt-6 border-t border-white/10", children: (0, jsx_runtime_1.jsx)("button", { onClick: onClose, className: "w-full bg-gradient-to-r from-gaming-primary to-gaming-secondary text-white py-3 rounded-lg font-medium hover:opacity-90 transition-opacity", children: "Got it!" }) })] }) }));
};
exports.TraitModal = TraitModal;
